
mp.jwt.secret.key=ThisIsMyNewSuperLongAndSecureKeyForHS256Testing1234567890abcdef
mp.jwt.lifetime.access.minutes=15
mp.jwt.lifetime.refresh.days=7
mp.jwt.issuer=HansonHuang

mp.jwt.verify.issuer=HansonHuang
mp.jwt.verify.key=ThisIsMyNewSuperLongAndSecureKeyForHS256Testing1234567890abcdef
mp.jwt.verify.signature.algorithm=HS256

media.upload.path=D:/Code/Java/media
media.base.url=http://localhost:8080/media