
jwt.secret.key=jO(zhTbo6Q36%8N0))Lh^FNoF^ZS)uGx5JRSM+7D19AuJ#!YkL5bu9RtvlI!rMh*I3K8s7_Ny*N#2^k7jXzioT@&FZZZjebGgL(hgFaO85Z9(dpkRYpK@6yAP#u5LD7cC#ViaD6dG1wbhj9vX9PIT6uK~~keY)8Ws^w6J*jlj9!E+Cb3n)GMqD6W)gPEF@KP7B)N*uLT0RrHq$j*2_BYsnSqeEOYMGcIL#5Kft_mlZoJKmY9Z6Uoj^%g*O^$+_#8
jwt.lifetime.access.minutes=15
jwt.lifetime.refresh.days=7
jwt.issuer=HansonHuang

mp.jwt.verify.issuer=HansonHuang
mp.jwt.verify.key=jO(zhTbo6Q36%8N0))Lh^FNoF^ZS)uGx5JRSM+7D19AuJ#!YkL5bu9RtvlI!rMh*I3K8s7_Ny*N#2^k7jXzioT@&FZZZjebGgL(hgFaO85Z9(dpkRYpK@6yAP#u5LD7cC#ViaD6dG1wbhj9vX9PIT6uK~~keY)8Ws^w6J*jlj9!E+Cb3n)GMqD6W)gPEF@KP7B)N*uLT0RrHq$j*2_BYsnSqeEOYMGcIL#5Kft_mlZoJKmY9Z6Uoj^%g*O^$+_#8

recaptcha.secret.key=6Lc2P-YqAAAAACHboO5IutjU8IQVQGT7iDfCgMYI
recaptcha.verify.url=https://www.google.com/recaptcha/api/siteverify

media.upload.path=D:/Code/Java/media
media.base.url=http://localhost:8080/media

jakarta.dataSource.DefaultDataSource.dataSourceClassName=com.mysql.cj.jdbc.MysqlDataSource
jakarta.dataSource.DefaultDataSource.url=jdbc:mysql://localhost:3306/ecommerce
jakarta.dataSource.DefaultDataSource.user=root
jakarta.dataSource.DefaultDataSource.password=Hanson242624